/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 s.glb --transform 
Files: s.glb [3.89MB] > s-transformed.glb [1.28MB] (67%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function S(props) {
  const { nodes, materials } = useGLTF('./models/s-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cloth.geometry} material={materials['FABRIC 1_FRONT_568544']} />
      <mesh geometry={nodes._mesh.geometry} material={materials.Material295605} position={[0.029, 1.504, -0.111]} rotation={[-2.66, 0.091, 3.057]} />
      <primitive object={nodes.body} />
    </group>
  )
}

useGLTF.preload('./models/s-transformed.glb')
